<a href="https://colab.research.google.com/github/edwardcalvinvazc-maker/Music-Recommendation-Engine/blob/main/Music_Recommendation_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
music_data = pd.read_csv('/content/M+U_dataset.csv')
music_data.head()

,timestamp,user_id,age,gender,location,device_type,listening_time_mins,sessions_per_day,time_of_day,day_of_week,...,skip_count,added_to_playlist,finished_song,time_spent_on_song,repeat_count,first_time_listening,context_type,song_position_in_session,session_duration_mins,liked
0,2021-01-01 00:00:00,1040,35,Female,US,Mobile,3,2,Afternoon,Weekday,...,2.0,0.0,1.0,109.0,1.0,0.0,Relax,10.0,31.0,0.0
1,2021-01-01 00:30:00,1000,45,Male,US,Mobile,28,1,Evening,Weekday,...,1.0,1.0,1.0,116.0,1.0,0.0,Workout,6.0,38.0,0.0
2,2021-01-01 01:00:00,1025,35,Other,US,Mobile,65,3,Afternoon,Weekday,...,0.0,0.0,0.0,172.0,1.0,0.0,Workout,8.0,25.0,1.0
3,2021-01-01 01:30:00,1049,45,Male,US,Smart Speaker,2,1,Afternoon,Weekend,...,0.0,0.0,1.0,172.0,0.0,1.0,Relax,8.0,49.0,0.0
4,2021-01-01 02:00:00,1011,45,Male,UK,Mobile,44,1,Evening,Weekday,...,0.0,1.0,0.0,178.0,1.0,0.0,Relax,2.0,25.0,0.0

In [3]:
music_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8137 entries, 0 to 8136
Data columns (total 49 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   timestamp                 8137 non-null   object
 1   user_id                   8137 non-null   int64
 2   age                       8137 non-null   int64
 3   gender                    8137 non-null   object
 4   location                  8137 non-null   object
 5   device_type               8137 non-null   object
 6   listening_time_mins       8137 non-null   int64
 7   sessions_per_day          8137 non-null   int64
 8   time_of_day               8137 non-null   object
 9   day_of_week               8137 non-null   object
 10  preferred_genre           8137 non-null   object
 11  preferred_artist          8137 non-null   object
 12  recent_skip_rate          8137 non-null   float64
 13  subscription_type         8137 non-null   object
 14  song_id                   8137 non-null   int64
 15  title                     8137 non-null   object
 16  artist                    8137 non-null   object
 17  album                     8137 non-null   object
 18  genre                     8137 non-null   object
 19  release_year              8137 non-null   int64
 20  language                  8137 non-null   object
 21  duration_sec              8137 non-null   int64
 22  popularity                8137 non-null   int64
 23  explicit                  8137 non-null   object
 24  tempo                     8137 non-null   float64
 25  key                       8137 non-null   int64
 26  mode                      8137 non-null   object
 27  time_signature            8137 non-null   int64
 28  energy                    8137 non-null   float64
 29  danceability              8137 non-null   float64
 30  acousticness              8137 non-null   float64
 31  instrumentalness          8137 non-null   float64
 32  liveness                  8136 non-null   float64
 33  valence                   8136 non-null   float64
 34  loudness                  8136 non-null   float64
 35  speechiness               8136 non-null   float64
 36  lyrics_sentiment          8136 non-null   object
 37  emotion_tag               8136 non-null   object
 38  play_count                8136 non-null   float64
 39  skip_count                8136 non-null   float64
 40  added_to_playlist         8136 non-null   float64
 41  finished_song             8136 non-null   float64
 42  time_spent_on_song        8136 non-null   float64
 43  repeat_count              8136 non-null   float64
 44  first_time_listening      8136 non-null   float64
 45  context_type              8136 non-null   object
 46  song_position_in_session  8136 non-null   float64
 47  session_duration_mins     8136 non-null   float64
 48  liked                     8136 non-null   float64
dtypes: float64(20), int64(10), object(19)
memory usage: 3.0+ MB

In [4]:
print('Columns with string values (object dtype):')
print(pd.DataFrame(music_data.select_dtypes(include='object').columns.tolist()))

Columns with string values (object dtype):
                    0
0           timestamp
1              gender
2            location
3         device_type
4         time_of_day
5         day_of_week
6     preferred_genre
7    preferred_artist
8   subscription_type
9               title
10             artist
11              album
12              genre
13           language
14           explicit
15               mode
16   lyrics_sentiment
17        emotion_tag
18       context_type

In [5]:
print('Missing values in each column:')
display(music_data.isnull().sum())

Missing values in each column:

timestamp                   0
user_id                     0
age                         0
gender                      0
location                    0
device_type                 0
listening_time_mins         0
sessions_per_day            0
time_of_day                 0
day_of_week                 0
preferred_genre             0
preferred_artist            0
recent_skip_rate            0
subscription_type           0
song_id                     0
title                       0
artist                      0
album                       0
genre                       0
release_year                0
language                    0
duration_sec                0
popularity                  0
explicit                    0
tempo                       0
key                         0
mode                        0
time_signature              0
energy                      0
danceability                0
acousticness                0
instrumentalness            0
liveness                    1
valence                     1
loudness                    1
speechiness                 1
lyrics_sentiment            1
emotion_tag                 1
play_count                  1
skip_count                  1
added_to_playlist           1
finished_song               1
time_spent_on_song          1
repeat_count                1
first_time_listening        1
context_type                1
song_position_in_session    1
session_duration_mins       1
liked                       1
dtype: int64

In [6]:

# Make a copy to avoid modifying the original DataFrame directly if not desired
music_data_label_encoded = music_data.copy()

# Identify categorical columns (object type)
string_cols = music_data_label_encoded.select_dtypes(include='object').columns

# Apply Label Encoding to each string column
for col in string_cols:
    le = LabelEncoder()
    music_data_label_encoded[col] = le.fit_transform(music_data_label_encoded[col])

print('DataFrame after Label Encoding:')
display(music_data_label_encoded.head())

print('\nInfo of the Label Encoded DataFrame:')
music_data_label_encoded.info()

DataFrame after Label Encoding:

,timestamp,user_id,age,gender,location,device_type,listening_time_mins,sessions_per_day,time_of_day,day_of_week,...,skip_count,added_to_playlist,finished_song,time_spent_on_song,repeat_count,first_time_listening,context_type,song_position_in_session,session_duration_mins,liked
0,0,1040,35,0,4,1,3,2,0,0,...,2.0,0.0,1.0,109.0,1.0,0.0,2,10.0,31.0,0.0
1,1,1000,45,1,4,1,28,1,1,0,...,1.0,1.0,1.0,116.0,1.0,0.0,4,6.0,38.0,0.0
2,2,1025,35,2,4,1,65,3,0,0,...,0.0,0.0,0.0,172.0,1.0,0.0,4,8.0,25.0,1.0
3,3,1049,45,1,4,2,2,1,0,1,...,0.0,0.0,1.0,172.0,0.0,1.0,2,8.0,49.0,0.0
4,4,1011,45,1,3,1,44,1,1,0,...,0.0,1.0,0.0,178.0,1.0,0.0,2,2.0,25.0,0.0

Info of the Label Encoded DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8137 entries, 0 to 8136
Data columns (total 49 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   timestamp                 8137 non-null   int64
 1   user_id                   8137 non-null   int64
 2   age                       8137 non-null   int64
 3   gender                    8137 non-null   int64
 4   location                  8137 non-null   int64
 5   device_type               8137 non-null   int64
 6   listening_time_mins       8137 non-null   int64
 7   sessions_per_day          8137 non-null   int64
 8   time_of_day               8137 non-null   int64
 9   day_of_week               8137 non-null   int64
 10  preferred_genre           8137 non-null   int64
 11  preferred_artist          8137 non-null   int64
 12  recent_skip_rate          8137 non-null   float64
 13  subscription_type         8137 non-null   int64
 14  song_id                   8137 non-null   int64
 15  title                     8137 non-null   int64
 16  artist                    8137 non-null   int64
 17  album                     8137 non-null   int64
 18  genre                     8137 non-null   int64
 19  release_year              8137 non-null   int64
 20  language                  8137 non-null   int64
 21  duration_sec              8137 non-null   int64
 22  popularity                8137 non-null   int64
 23  explicit                  8137 non-null   int64
 24  tempo                     8137 non-null   float64
 25  key                       8137 non-null   int64
 26  mode                      8137 non-null   int64
 27  time_signature            8137 non-null   int64
 28  energy                    8137 non-null   float64
 29  danceability              8137 non-null   float64
 30  acousticness              8137 non-null   float64
 31  instrumentalness          8137 non-null   float64
 32  liveness                  8136 non-null   float64
 33  valence                   8136 non-null   float64
 34  loudness                  8136 non-null   float64
 35  speechiness               8136 non-null   float64
 36  lyrics_sentiment          8137 non-null   int64
 37  emotion_tag               8137 non-null   int64
 38  play_count                8136 non-null   float64
 39  skip_count                8136 non-null   float64
 40  added_to_playlist         8136 non-null   float64
 41  finished_song             8136 non-null   float64
 42  time_spent_on_song        8136 non-null   float64
 43  repeat_count              8136 non-null   float64
 44  first_time_listening      8136 non-null   float64
 45  context_type              8137 non-null   int64
 46  song_position_in_session  8136 non-null   float64
 47  session_duration_mins     8136 non-null   float64
 48  liked                     8136 non-null   float64
dtypes: float64(20), int64(29)
memory usage: 3.0 MB

In [7]:
# 1. DEFINE PIPELINE BOUNDARIES
classifier_target = 'liked'
regressor_target = 'time_spent_on_song' # Assuming 'time_spent_on_song' is the intended regressor target

# Identify columns that are unique identifiers or should be excluded from features
# based on the blueprint's guidance.
text_id_columns = ['timestamp', 'user_id', 'song_id', 'title', 'artist', 'album', 'preferred_artist']

# 2. ELIMINATE TARGET LEAKAGE AND IDS
# Create a copy of the original music_data to work with
df_processed = music_data.copy()

# Separate target variables
y_class = df_processed[classifier_target]
y_reg = df_processed[regressor_target]

# Define all columns to be dropped from the feature matrix X
columns_to_drop = [classifier_target, regressor_target] + text_id_columns
X = df_processed.drop(columns=[col for col in columns_to_drop if col in df_processed.columns], errors='ignore')

print(f"Original DataFrame shape: {music_data.shape}")
print(f"Feature matrix (X) shape after dropping targets and IDs: {X.shape}")
print(f"Classification target (y_class) shape: {y_class.shape}")
print(f"Regression target (y_reg) shape: {y_reg.shape}")

Original DataFrame shape: (8137, 49)
Feature matrix (X) shape after dropping targets and IDs: (8137, 40)
Classification target (y_class) shape: (8137,)
Regression target (y_reg) shape: (8137,)

In [8]:
# 3. EXECUTE STRUCTURAL ENCODING
# Convert categorical features to Pandas 'category' types
# Using 'location' for 'user_region' as suggested by the blueprint
categorical_features = [
    'gender', 'location', 'device_type', 'time_of_day', 'day_of_week',
    'preferred_genre', 'subscription_type', 'genre', 'language', 'explicit',
    'mode', 'lyrics_sentiment', 'emotion_tag', 'context_type'
]

for col in categorical_features:
    if col in X.columns:
        X[col] = X[col].astype('category')

print('\nFeatures DataFrame (X) after converting categorical columns to `category` dtype:')
X.info()

Features DataFrame (X) after converting categorical columns to `category` dtype:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8137 entries, 0 to 8136
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       8137 non-null   int64
 1   gender                    8137 non-null   category
 2   location                  8137 non-null   category
 3   device_type               8137 non-null   category
 4   listening_time_mins       8137 non-null   int64
 5   sessions_per_day          8137 non-null   int64
 6   time_of_day               8137 non-null   category
 7   day_of_week               8137 non-null   category
 8   preferred_genre           8137 non-null   category
 9   recent_skip_rate          8137 non-null   float64
 10  subscription_type         8137 non-null   category
 11  genre                     8137 non-null   category
 12  release_year              8137 non-null   int64
 13  language                  8137 non-null   category
 14  duration_sec              8137 non-null   int64
 15  popularity                8137 non-null   int64
 16  explicit                  8137 non-null   category
 17  tempo                     8137 non-null   float64
 18  key                       8137 non-null   int64
 19  mode                      8137 non-null   category
 20  time_signature            8137 non-null   int64
 21  energy                    8137 non-null   float64
 22  danceability              8137 non-null   float64
 23  acousticness              8137 non-null   float64
 24  instrumentalness          8137 non-null   float64
 25  liveness                  8136 non-null   float64
 26  valence                   8136 non-null   float64
 27  loudness                  8136 non-null   float64
 28  speechiness               8136 non-null   float64
 29  lyrics_sentiment          8136 non-null   category
 30  emotion_tag               8136 non-null   category
 31  play_count                8136 non-null   float64
 32  skip_count                8136 non-null   float64
 33  added_to_playlist         8136 non-null   float64
 34  finished_song             8136 non-null   float64
 35  repeat_count              8136 non-null   float64
 36  first_time_listening      8136 non-null   float64
 37  context_type              8136 non-null   category
 38  song_position_in_session  8136 non-null   float64
 39  session_duration_mins     8136 non-null   float64
dtypes: category(14), float64(18), int64(8)
memory usage: 1.7 MB

In [9]:
# Perform the train-test split on features (X) and both target variables (y_class, y_reg)
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_class, y_reg,
    test_size=0.20,       # 20% reserved for unbiased testing
    random_state=42       # Reproducible shuffling seed
)

print(f"\nPipeline Preparation Complete.")
print(f"Training Matrix Dimensions: {X_train.shape}")
print(f"Testing Matrix Dimensions: {X_test.shape}")
print(f"Classification Training Target Dimensions: {y_class_train.shape}")
print(f"Classification Testing Target Dimensions: {y_class_test.shape}")
print(f"Regression Training Target Dimensions: {y_reg_train.shape}")
print(f"Regression Testing Target Dimensions: {y_reg_test.shape}")

Pipeline Preparation Complete.
Training Matrix Dimensions: (6509, 40)
Testing Matrix Dimensions: (1628, 40)
Classification Training Target Dimensions: (6509,)
Classification Testing Target Dimensions: (1628,)
Regression Training Target Dimensions: (6509,)
Regression Testing Target Dimensions: (1628,)

## Train XGBoost Classifier

### Subtask:
Initialize and train an XGBoost Classifier model using `X_train` and `y_class_train` to predict the 'liked' status.

## Hyperparameter Tuning with RandomizedSearchCV

### Subtask:
Use `RandomizedSearchCV` to find the best hyperparameters for the XGBoost Classifier.

In [10]:
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform, randint

# Define the parameter distribution for RandomizedSearchCV
param_distributions = {
    'n_estimators': randint(100, 500),
    'learning_rate': uniform(0.01, 0.2),
    'max_depth': randint(3, 10),
    'subsample': uniform(0.6, 0.4),
    'colsample_bytree': uniform(0.6, 0.4),
    'gamma': uniform(0, 0.5),
    'reg_alpha': uniform(0, 0.5),
    'reg_lambda': uniform(0, 0.5)
}

# Initialize the XGBoost Classifier with the same fixed parameters as before
# (tree_method, objective, eval_metric) and a random_state.
xgb_clf_base = xgb.XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    tree_method='hist',
    enable_categorical=True, # Changed to True to handle categorical columns
    random_state=42
)

# Initialize RandomizedSearchCV
random_search_clf = RandomizedSearchCV(
    estimator=xgb_clf_base,
    param_distributions=param_distributions,
    n_iter=50,  # Number of parameter settings that are sampled. Adjust as needed.
    scoring='roc_auc',  # Or 'accuracy', 'f1', etc., appropriate for classification
    cv=3,  # 3-fold cross-validation
    verbose=1, # Prints progress messages
    random_state=42,
    n_jobs=-1 # Use all available cores
)

# Fit RandomizedSearchCV to the training data
print("Starting RandomizedSearchCV for XGBoost Classifier...")
random_search_clf.fit(X_train, y_class_train)

print("RandomizedSearchCV for XGBoost Classifier complete.")
print(f"Best parameters found: {random_search_clf.best_params_}")
print(f"Best ROC AUC score: {random_search_clf.best_score_:.4f}")

Starting RandomizedSearchCV for XGBoost Classifier...
Fitting 3 folds for each of 50 candidates, totalling 150 fits
RandomizedSearchCV for XGBoost Classifier complete.
Best parameters found: {'colsample_bytree': np.float64(0.749816047538945), 'gamma': np.float64(0.4753571532049581), 'learning_rate': np.float64(0.15639878836228102), 'max_depth': 7, 'n_estimators': 120, 'reg_alpha': np.float64(0.07800932022121826), 'reg_lambda': np.float64(0.07799726016810132), 'subsample': np.float64(0.6232334448672797)}
Best ROC AUC score: 0.5110

In [11]:
import xgboost as xgb

# Initialize the XGBoost Classifier with the best parameters from RandomizedSearchCV
xgb_classifier = xgb.XGBClassifier(
    **random_search_clf.best_params_,
    objective='binary:logistic',
    eval_metric='logloss',
    tree_method='hist',
    enable_categorical=True,
    random_state=42
)

# Train the classifier
xgb_classifier.fit(X_train, y_class_train)

print("XGBoost Classifier training complete with best hyperparameters.")

XGBoost Classifier training complete with best hyperparameters.

In [12]:

# 1. Initialize the baseline regressor with your native category setting
base_reg = xgb.XGBRegressor(
    tree_method="hist",
    enable_categorical=True,
    objective="reg:squarederror"
)

# 2. Define the hyperparameter grid distributions
param_distributions_reg = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [3, 4, 5, 6],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8, 0.9]
}

# 3. Set up the automated cross-validation searcher
tuned_reg_search = RandomizedSearchCV(
    estimator=base_reg,
    param_distributions=param_distributions_reg,
    n_iter=10,
    scoring='neg_root_mean_squared_error',  # Optimizing to minimize your timing errors
    cv=3,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# 4. Fit the search space using your continuous training array targets
print("Starting Regressor Hyperparameter Optimization Search...")
tuned_reg_search.fit(X_train, y_reg_train)

print("\n=== REGRESSOR TUNING COMPLETE ===")
print("Best Negative RMSE Score Found:", tuned_reg_search.best_score_)
print("Best Regressor Hyperparameters :", tuned_reg_search.best_params_)

Starting Regressor Hyperparameter Optimization Search...
Fitting 3 folds for each of 10 candidates, totalling 30 fits

=== REGRESSOR TUNING COMPLETE ===
Best Negative RMSE Score Found: -30.065744195775522
Best Regressor Hyperparameters : {'subsample': 0.8, 'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.01, 'colsample_bytree': 0.9}